### PR TITLE
Added WGS directory structure schema

### PR DESCRIPTION
**Pull request by icaoberg**
The directory structure for the whole genome sequence assay type is nothing but a link to `fastq.yaml`. 

From my understanding, this should suffice for now.

### CODE REVIEW

**Review by jswelling — COMMENTED** [review]
You know the 'extras/.*' regex subsumes the 'extras/thumbnail.(png|jpg)' regex, right?  You don't actually need the second one?  If you want it there for stylistic reasons I'm OK with it.

**Comment by icaoberg** [comment]
> You know the 'extras/.*' regex subsumes the 'extras/thumbnail.(png|jpg)' regex, right? You don't actually need the second one? If you want it there for stylistic reasons I'm OK with it.

@jswelling agree. Howver, the file `wgs.yaml` is a link to `fastq.yaml`. If we modify `fastq.yaml`, the change will affect at least 4 directory structure schemas.

What do you think I should do? Should I update `fastq.yaml`?

**Comment by jswelling** [comment]
Wait, I just figured out that the 'extras' entry is hard-coded in schema_loader.py .  It's not coming from a .yaml file at all!  So no, no change is necessary.  I'll approve the merge as it stands.  Sorry for the confusion.

**Review by jswelling — APPROVED** [review]
Accepted- I hadn't understood that the redundant entry to accept thumbnails in extras was coming from code outside this PR.

**Pull request merged**
