### PR TITLE
Mccalluc/3d imc

### PR DESCRIPTION
**Pull request by mccalluc**
- @cebriggs7135 - Check that the list of fields is correct.
- @jswelling - This introduces a new assay type: Now that there is the assay service, what should I do to try to bring this in sync with that? Does there need to be a corresponding PR somewhere else?

### CODE REVIEW

**Review by jswelling — COMMENTED** [review]
The new type will need to be added to https://github.com/hubmapconsortium/search-api/blob/master/src/search-schema/data/definitions/enums/assay_types.yaml .  I'm not clear on how you're supposed to create a branch and a PR to integrate with Bill's current deployment process.

**Comment by cebriggs7135** [comment]
@mccalluc  You say above " factor out roi fields". That sounds like you've removed them. That's incorrect. The roi fields remain in 3D IMC.

**Comment by mccalluc** [comment]
> That sounds like you've removed them.

@cebriggs7135 -- No: That's a misunderstanding. "factoring out" is a metaphor, based on the operation in algebra:
```
ax + bx = (a + b)x
```
... except in this case, we can think of `ax` as being the IMC fields, `bx` as being the 3d IMC fields. I've pulled out the parts they two assays share, and reference these shared parts from each assay.

You can see that there are no changes to imc.md in this PR. I would like you to review imc3d.md, to confirm that it has the correct fields.

**Comment by mccalluc** [comment]
> The new type will need to be added to ...

Filed https://github.com/hubmapconsortium/search-api/pull/237 ... I don't think it's necessary to wait until that is merged to merge this, but defer to your judgement.

**Review by cebriggs7135 — APPROVED** [review]

**Comment by mccalluc** [comment]
@jswelling - ping - https://github.com/hubmapconsortium/search-api/pull/237 is open - I don't think this PR needs to block on that, but I'll defer to you.

**Review by jswelling — APPROVED** [review]
Looks fine, but directory schema still needed.

**Pull request merged**
