### PR TITLE
IMC directory schema

### LINKED ISSUE #447: Directory schema for imc

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #447

### CODE REVIEW

**Review by cebriggs7135 — COMMENTED** [review]
I Slacked Chuck about running this list of directory content past Michele, our IMC expert.

**Comment by mccalluc** [comment]
@cebriggs7135 : To clarify, you're reaching out, and will update here?

**Comment by icaoberg** [comment]
@mccalluc I couldn't resolve the conflicts with the YAML file because it wants me to resolve the issues with the CHANGELOG as well. The YAML file seems fine, I confirmed the directory structure with the published dataset `HBM839.VWVF.894`.

**Review by icaoberg — APPROVED** [review]
Confirmed directory structure schema with a published dataset in portal.

**Comment by mccalluc** [comment]
Closing PR to clarify that I do not have a role in authoring directory schemas... but I'll keep the branch around, in case it's useful.

**Pull request closed without merging**
