### PR TITLE
Update lc_temp_value.yaml

### PR DESCRIPTION
**Pull request by cebriggs7135**
lc_temp may not be applicable in certain cases (no heating involved). Make this field optional, as is the corresponding lc_temp_unit field.

### CODE REVIEW

**Comment by mccalluc** [comment]
Going forward, I think it would be good if you regenerated the documentation on your PRs.

**Review by mccalluc — COMMENTED** [review]
Going forward, I think I would be good if you regenerated the docs for your PRs.

**Comment by cebriggs7135** [comment]
Happy to oblige. Can you show me the process?

**Comment by mccalluc** [comment]
@cebriggs7135 :
```
git checkout cebriggs7135-patch-4
# I would encourage you to use distinct branch names going forward.
git pull
./test.sh
# Will produce the same error as in CI; Error message should suggest a fix.
git add .
git commit -m 'regenerate'
git push
```

**Comment by cebriggs7135** [comment]
@mccalluc Please clarify next steps so I can regenerate the lcms doc with the lcms_temp_value field requirement change.

**Pull request merged**
