### PR TITLE
Add release_date

### LINKED ISSUE #969: add metadata schema version release dates to the documentation
In order to help support transition to new metadata schema versions, the release date for a schema should be included in the YAML and the documentation. 

Current blocker: we don't have a final decision on who define the release date and how it will be communicated. @pecan88 is currently trying to figure out what the process will be.

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #969. Filled in a fake value for the AF schema. @pecan88 -- I believe you have responsibility for identifying a schema that that this should actually be applied to? Filing as draft until that information is available.

### CODE REVIEW

**Comment by mccalluc** [comment]
@ngehlenborg / @cebriggs7135 -- What is needed to move this forward?

**Comment by mccalluc** [comment]
@cebriggs7135 gave antibodies as an example that could use a release date, so I've filled that in.

**Comment by mccalluc** [comment]
Chris clarifies that the antibodies date is just an example: I'll look through the change log and find an accurate example in the recent past.

**Review by ngehlenborg — APPROVED** [review]

**Review by cebriggs7135 — COMMENTED** [review]
approved

**Pull request merged**
