### PR TITLE
Resolves issues submitted by Vanderbilt related to PAS stained and AF

### PR DESCRIPTION
**Pull request by icaoberg**
This branch resolves issues #700 #711 #719 #712 #710 submitted by NHPatterson.

### CODE REVIEW

**Comment by mccalluc** [comment]
Please link this PR to the issues it closes, either manually, or [using keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by NHPatterson** [comment]
@icaoberg This + #699 (may need to be merged into this PR) gets us to "No errors!" for our upcoming submission!

**Review by jswelling — COMMENTED** [review]
Is the .czi file required?  If so, I think it's our first required .czi .  I recently turned off the parsing/validation of .czi files provided by the metadata extractor because of problems with availability of the required module under python 3.8.  That's only relevant if we want to do anything with it.  I do suspect this file should be optional though.

**Comment by icaoberg** [comment]
> Is the .czi file required? If so, I think it's our first required .czi . I recently turned off the parsing/validation of .czi files provided by the metadata extractor because of problems with availability of the required module under python 3.8. That's only relevant if we want to do anything with it. I do suspect this file should be optional though.

@NHPatterson could you answer @jswelling  so that I approve/update this PR? Thanks.

**Comment by jswelling** [comment]
I will approve now, but we want that answer from @NHPatterson

**Review by jswelling — APPROVED** [review]

**Comment by icaoberg** [comment]
> I will approve now, but we want that answer from @NHPatterson

I mean by default, all files are set to optional. So I am guessing the CZI file is intended to be optional too. If it is not meant to be optional, then I can open another branch and do a quick-fix.

**Comment by icaoberg** [comment]
@NHPatterson you should be able to pull master and try to validate. If it doesn't work open a new ticket and I will do my best to tackle the issue today.

**Comment by NHPatterson** [comment]
@icaoberg Validates perfectly well when pulled from master for all our data now. Thanks!

@jswelling The .czi file (a vendor microscopy image file) could be optional as well although I think always storing the rawest form of the data somewhere is a good idea. It could very well also be that other groups collect this modality and have raw data with a different extension because they've collected it on another vendor's instrumentation.

**Pull request merged**
