### PR TITLE
Cebriggs7135 add links to examples

### PR DESCRIPTION
**Pull request by cebriggs7135**
Added links to assay examples in description.mds for 5 assays. Protected datasets were not included nor were assays for which we currently have no data.

### CODE REVIEW

**Comment by cebriggs7135** [comment]
@mccalluc I regenerated these docs on my branch. Next, Chuck will review and merge to main??

**Comment by mccalluc** [comment]
@cebriggs7135 -- Almost there: You can see that there is still a test failure: If you click on the red X [you'll see this](https://github.com/hubmapconsortium/ingest-validation-tools/runs/4071478801?check_suite_focus=true#step:6:227):
```
Update CHANGELOG.md
```

**Comment by cebriggs7135** [comment]
@mccalluc I've clicked the red x's above and don't see that. They show something about portal CI.
I did this in Visual Studio Code & some in the terminal in Rstudio.

**Comment by cebriggs7135** [comment]
@mccalluc Try merging now, please?

**Review by mccalluc — APPROVED** [review]

**Pull request merged**
