### PR TITLE
Mccalluc/update ims

### PR DESCRIPTION
**Pull request by mccalluc**
Replace #1044

<details><summary>better diff</summary>

```diff
diff -U 10 docs/ims/v{2,3}.yaml
--- docs/ims/v2.yaml	2022-02-07 15:11:34.000000000 -0500
+++ docs/ims/v3.yaml	2022-02-07 15:51:19.000000000 -0500
@@ -1,18 +1,18 @@
 # Generated YAML: PRs should not start here!
 description_md: This schema is for imaging mass spectrometry (IMS).
 doc_url: https://portal.hubmapconsortium.org/docs/assays/maldi-ims
 fields:
 - Shared by all types
 - constraints:
     enum:
-    - '2'
+    - '3'
     required: true
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
   description: Version of the schema to use when validating this metadata.
   name: version
 - constraints:
     required: true
   custom_constraints:
     forbid_na: true
@@ -160,28 +160,27 @@
   name: acquisition_instrument_model
 - Unique to this type
 - constraints:
     enum:
     - MALDI
     - MALDI-2
     - LDI
     - LA
     - SIMS-C60
     - SIMS-H2O
-    - ESI
     - nanoDESI
     required: true
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
   description: The ion source type used for surface sampling (MALDI, MALDI-2, DESI,
-    or SIMS) or LC-MS/MS data acquisition (nESI)
+    nanoDESI or SIMS).
   name: ms_source
 - constraints:
     enum:
     - negative ion mode
     - positive ion mode
     - negative and positive ion mode
     required: true
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
@@ -197,30 +196,30 @@
   type: number
 - constraints:
     required: true
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
   description: The high value of the scanned mass range for MS1. (unitless)
   name: mz_range_high_value
   type: number
 - constraints:
-    required: false
+    required: true
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
   description: "The MS1 resolving power defined as m/\u2206m where \u2206m is the\
     \ FWHM for a given peak with a specified m/z (m). (unitless)"
   name: mass_resolving_power
   type: number
 - constraints:
-    required: false
+    required: true
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
   description: The peak (m/z) used to calculate the resolving power.
   name: mz_resolving_power
   type: number
 - constraints:
     enum:
     - TIMS
     - TWIMS
@@ -308,21 +307,21 @@
     forbid_na: true
     sequence_limit: 3
   description: The model number/name of the instrument used to prepare the sample
     for the assay
   name: preparation_instrument_model
 - constraints:
     enum:
     - CHB
     - DHB
     - SA
-    required: true
+    required: false
   custom_constraints:
     forbid_na: true
     sequence_limit: 3
   description: The matrix is a compound of crystallized molecules that acts like a
     buffer between the sample and the laser. It also helps ionize the sample, carrying
     it along the flight tube so it can be detected.
   name: preparation_maldi_matrix
 - constraints:
     required: false
   custom_constraints:
```

</details>

@ngehlenborg -- In the past you have expressed concern about small incremental changes to schemas: Not sure if this falls under that, or what the alternative is.

### CODE REVIEW

**Review by cebriggs7135 — APPROVED** [review]

**Comment by mccalluc** [comment]
@cebriggs7135 will look into the history of the submissions: If there are datasets that require the looser schema, Nils would prefer that we make the changes in place, ie, similar to how we've handled small typo corrections in the past.

**Comment by mccalluc** [comment]
@cebriggs7135 -- Can you clarify whether this PR is go or no-go?

**Review by cebriggs7135 — COMMENTED** [review]
I approve the changes but believe this does not warrant a new version.

**Comment by mccalluc** [comment]
> I approve the changes but believe this does not warrant a new version.

This PR creates a new version. If you don't want a new version, then it shouldn't be approved. Please only approve if it's exactly what you want. I am juggling multiple PRs and it places a burden on me if I can't trust the approved flag. Thank you.

**Pull request closed without merging**
