### PR TITLE
J uranic/publication assay schemas

### PR DESCRIPTION
**Pull request by j-uranic**
Uploaded directory schema and table schema .yaml files for new Publication assay.

### CODE REVIEW

**Comment by jswelling** [comment]
I have tested this successfully against the prototype Publication directory cff698cf72e09e712afd7b1905ce9dca on TEST.

**Review by jswelling — CHANGES_REQUESTED** [review]
I think the regex element '/.+\.json' actually permits additional '/' elements and thus permits subdirectories before the filename, so the elaborated version at line 14 is unnecessary.

**Comment by j-uranic** [comment]
> I think the regex element '/.+.json' actually permits additional '/' elements and thus permits subdirectories before the filename, so the elaborated version at line 14 is unnecessary.

(Vignettes|vignettes)/(Vignette|vignette)_\d+/**.+/**.+\.json'

I had included the .+/ (bolded above) to accommodate the possibility of a subdirectory in the example directory tree ("mysubdir" below). If it's not needed, it can be deleted.

```
- vignettes
- - vignette_01
- - - mysubdir
- - - - conf.json
```

**Comment by ngehlenborg** [comment]
No subdirectories within the vignette directories are needed or should be allowed. Can we remove that option?

**Comment by j-uranic** [comment]
> No subdirectories within the vignette directories are needed or should be allowed. Can we remove that option?

Sure, that mapping has been removed.

**Comment by j-uranic** [comment]
Thanks for the clarification, I updated it to /[^/]+\.json and now it is only matching examples without a subdirectory.

**Review by jswelling — APPROVED** [review]

**Review by jswelling — APPROVED** [review]
My approval doesn't really count here, since a bunch of the changes are actually mine.

**Pull request merged**
